openapi: '3.0.3'
info:
  title: Contact API
  version: '1.0'
servers:
  - url: http://localhost:8000/
paths:
  /api/contacts:
    post:
      description: Create a new contact
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
      requestBody:
        description: Create a new contact
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: Successfully created contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                      error:
                        type: object
    get:
      description: Search data contact
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
        - name: name
          in: query
          required: true
          schema:
            type: string
        - name: phone
          in: query
          schema:
            type: string
        - name: email
          in: query
          schema:
            type: string
        - name: size
          in: query
          schema:
            type: string
        - name: page
          in: query
          schema:
            type: string
      responses:
        '200':
          description: Successfully searched contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: number
                        first_name:
                          type: string
                        last_name:
                          type: string
                        email:
                          type: string
                        phone:
                          type: string
                        errors:
                            type: object
                        meta:
                            type: object
  /api/contacts/{id}:
    put:
      description: Update a contact
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the contact to update
      requestBody:
        description: Update contact data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                first_name:
                  type: string
                last_name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
      responses:
        '200':
          description: Successfully updated contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                  errors:
                    type: object
    get:
      description: Get a contact by ID
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: ID of the contact to retrieve
      responses:
        '200':
          description: Successfully retrieved contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: number
                      first_name:
                        type: string
                      last_name:
                        type: string
                      email:
                        type: string
                      phone:
                        type: string
                  errors:
                    type: object
    delete:
      description: Remove a contact
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
          description: Bearer token for authentication
      responses:
        '200':
          description: Successfully deleted contact
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
